--- #YAML:1.0
name:                XML-Compile-RPC
version:             0.11
abstract:            XML-RPC client
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Report:                   0.25
    LWP::UserAgent:                0
    Test::More:                    0.54
    Test::Pod:                     1.00
    Time::HiRes:                   0
    XML::Compile:                  1.08
    XML::Compile::Cache:           0.92
    XML::Compile::Tester:          0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
