---
abstract: 'XML-RPC client'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-RPC
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  Log::Report: 0.28
  Test::More: 0.54
  Time::HiRes: 0
  XML::Compile: 1.08
  XML::Compile::Cache: 0.92
  XML::Compile::Tester: 0.05
version: 0.17
